addpath( ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/lib', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/lib/t', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/data', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/most/lib', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/most/lib/t', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/mp-opt-model/lib', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/mp-opt-model/lib/t', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/mips/lib', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/mips/lib/t', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/mptest/lib', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/mptest/lib/t', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/extras/maxloadlim', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/extras/maxloadlim/tests', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/extras/maxloadlim/examples', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/extras/misc', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/extras/reduction', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/extras/sdp_pf', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/extras/se', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/extras/smartmarket', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/extras/state_estimator', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/extras/syngrid/lib', ...
    '/Users/bguo/Library/Mobile Documents/com~apple~CloudDocs/Research Paper/zero-th order optimization sum/power system experiments/packages/matpower7.1/extras/syngrid/lib/t', ...
    '-end' );
